### ISSUE TITLE
Consumer Flow: Internal Feedback Items

### ISSUE THREAD

**Issue by Abhi2102** [NationalDataPlatform/NationalDataPlatform#115]
Blog

- [x] - Copy blog design from Assam OCI
- [x] - Ecosystem -> platform in desc

Connect

- [x] connect new category 'Newsletter Subscription'
- [x] - Improve design
- [x] - Clear fields after submit

Others

- [x] - Change accessibility icon
- [x] - Stick the navbar on top

Home

- [x] remove static content
- [x] header change organization to contributors
- [x] clickable links
- [x] spacing on home page - search byline explore x number of datasets from y contributors
- [x] sector page
- [x] explorer all sectors page
- [x] contributor logo spacing , logo chopped off
- [x] avg rating disable
- [x] download disable
- [x] spacing below org home page
- [x] start reg move up
- [x] start reg direct to data.gov.in reg page
- [x] share illustration for reg banner
- [x] featured dataset add org image
- [x] featured dataset check date is dynamic
- [x] feature make org clickable
- [x] feature change date to original instead of date create on ndp
- [x] explore dataset certain not working
- [ ] about national dataplatform the logo size and resolution
- [x] footer links
- [x] sitemap
- [x] data.gov.in linked twitter
- [x] spacing between logo and subscribe for updates
- [x] whole thing in the bottom needs to go
- [x] remove subscribe for updates

Organization

- [x] click on dataset whole pane needs to be clickable
- [x] data not getting filtered by org
- [x] move dataset count below

About

- [x] title content and partner content
- [x] creators - NIC should come first
- [x] links not clickable 
- [x] nic - change owner to partner
- [x] developers section remove

Dataset Landing

- [ ] dataset migration licenses
- [x] filter deselecting one click not working
- [x] remove test dataset
- [x] popularity sort
- [x] tag font on dtatset card, count 
- [x] filter should be sorted
- [x] remove tags filter
- [x] csv, xls, pdf contrast
- [x] sort remove popular
- [x] name and view dataset clickable

Dataset explorer

- [x] org details not justified
- [x] about data - author and maintainer
- [x] diable all unclikable tabs
- [x] data api - show all resources
- [x] schema info - tabs
- [x] updated weekly - disable
- [x] tabs - about , data , api
- [x] updated weekly, clsoe access - remove
- [x] add license
- [x] remove total downloads
- [x] remove rating
- [x] get access - change with download data package
- [x] org on right - remove cdo section - contact info
- [x] table color
- [ ] seggregation of top and bottom section coloring
- [x] related dataset top and bottom spacing
- [x] social buttons make working - save embed share
- [x] make org names and links clickable
- [x] make org desc card std size

**Comment by bhavabhuthi** [comment]
Raised #154 for Sectors related changes. Will mark done once the PR is accepted.
