### ISSUE TITLE
Home Page: List of changes for next Release

### ISSUE THREAD

**Issue by bhavabhuthi** [NationalDataPlatform/NationalDataPlatform#57]
Header section
- [x] Remove Dropdown from the Header Page

Explore by Sectors section
- [ ] Finalize sectors and Map the icons accordingly

About Section
- [x] Move About the Platform towards bottom above the Footer

Contributor section
- [x] Add 'Contributor Organizations' name for the Partner Carousal section
- [ ] Move scroller above the Contributor details part
- [ ] Update the highlight mechanism

Banner section
- [ ] Finalize the banner and Update accordingly

Dataset Carousal section
- [ ] Move Arrow to the Corner or Decouple from the details of the dataset

Accessibility section
- [ ] Add the Accessibility section
- [ ] Link the functionality with the respective application page

**Comment by ruthvik129** [comment]
- [ ] Fix searchbar on the homepage to support on all browsers
- [ ] Fix dotted line for active carousel item
- [ ] Fix semantics of footer to have HTML semantic 
- [ ] Fix alignment of the button in the Home banner
