### ISSUE TITLE
Overall Icons & Images

### ISSUE THREAD

**Issue by bhavabhuthi** [NationalDataPlatform/NationalDataPlatform#94]
Replace all the placeholder images with respective icons and images.

- [x] Home Page - Explore by Sections, Sector Icons
- [x] Home Page - About platform, Description Icons
- [x] Home Page - Footer section, Social Media Icons & Creator Images
- [x] Dataset Listing Page - Dataset Card licence and other Icons
- [x] Dataset Landing Page - Dataset description section Icons
- [x] Blog Listing Page - Blog card wise Images

**Comment by PixeledCode** [comment]
closed with #115
